[versions]
androidGradlePlugin = "8.5.2"
kotlin = "2.0.20"
ksp-version = "2.0.20-1.0.24"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }

